# Generated by Django 4.2.1 on 2023-07-30 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbots", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatbotconfig",
            old_name="session",
            new_name="chatbot",
        ),
        migrations.RenameField(
            model_name="chatbotreply",
            old_name="session",
            new_name="chatbot",
        ),
        migrations.RenameField(
            model_name="prompt",
            old_name="session",
            new_name="chatbot",
        ),
    ]
