# Generated by Django 4.2.1 on 2023-08-05 06:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbots', '0002_rename_session_chatbotconfig_chatbot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbot',
            name='max_tokens',
            field=models.PositiveIntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=255),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='stream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='temperature',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=5),
        ),
        migrations.DeleteModel(
            name='ChatBotConfig',
        ),
    ]
